### PR TITLE
data: Data Flow in app when raw items updated

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/openactive/conformance-services/issues/79
https://github.com/openactive/conformance-services/issues/42

### CODE REVIEW

**Comment by odscjames** [comment]
@rhiaro This needs some tests work but you may want to look at what I'm doing here and chat with me to check out the proposed workflow

**Comment by odscjames** [comment]
[Bug in process when raw item updated](https://trello.com/c/T9ktBR7B/127-bug-in-process-when-raw-item-updated)

**Comment by odscjames** [comment]
[Make deletes cascade from source to normalised data](https://trello.com/c/2nIw5IhG/23-make-deletes-cascade-from-source-to-normalised-data)

**Comment by odscjames** [comment]
I also run a manual test by putting some data in DB, 

Running:
```

select count(*) from raw_data where normalised  = TRUE;  
select count(*) from raw_data where validation_done = TRUE;  
select count(*) from normalised_data where data_deleted = FALSE; 
select count(*) from normalised_data_profile_results ;

```


Then started again:

    update publisher_feed set raw_next_url=NULL;

Then run only the downlead raw data process and you should see every one of those 3 counts going down - and I did!

**Review by rhiaro — APPROVED** [review]

**Pull request merged**
